spring.application.name=list
spring.datasource.url=jdbc:postgresql://localhost:5432/TodoList
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.resources.add-mappings=false
api.debug=true
spring.hateoas.use-hal-as-default-json-media-type=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
info.app.name=Lista de Tarefas API
info.app.description=APT REST para gerenciamento de tarefas
info.app.version=1.0.0