name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 26
        uses: actions/setup-java@v4
        with:
          java-version: "26"
          distribution: "temurin"
          cache: maven

      - name: Rodar testes
        run: ./mvnw clean test
